# Generated by Django 3.2.6 on 2021-08-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytask',
            options={'ordering': ['category_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='categorytask',
            name='category_name',
            field=models.CharField(help_text='укажите категорию задач', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category_task',
            field=models.ForeignKey(help_text='выберите категию задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.categorytask', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='low', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(help_text='что нужно', max_length=40, verbose_name='Задача'),
        ),
    ]
