# Generated by Django 3.2.6 on 2021-09-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210830_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='укажите категорию задачи', max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_name'],
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='category_task',
        ),
        migrations.DeleteModel(
            name='CategoryTask',
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(help_text='выберите категию задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.category', verbose_name='Категория'),
        ),
    ]
