# Generated by Django 3.2.6 on 2021-09-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210919_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
